name: Update GIF in README

on:
  schedule:
    - cron: '0 0 * * *' # Exécute tous les jours à minuit

jobs:
  update_gif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get a random GIF
        id: get_gif
        run: |
          # Remplace cette URL par celle de l'API que tu utilises pour obtenir un GIF aléatoire
          GIF_URL=$(curl -s 'https://api.giphy.com/v1/gifs/random?api_key=YOUR_API_KEY&tag=&rating=g' | jq -r '.data.images.original.url')
          echo "::set-output name=gif_url::$GIF_URL"

      - name: Update README.md with new GIF
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          GIF_URL="${{ steps.get_gif.outputs.gif_url }}"

          # Remplacer le contenu entre les balises de commentaire
          sed -i.bak "/<!-- Start of Trending GIF Section -->/,/<!-- End of Trending GIF Section -->/ {
            /<!-- Start of Trending GIF Section -->/! { 
              /<!-- End of Trending GIF Section -->/! d 
            } 
            s|![Trending GIF](.*)|![Trending GIF]($GIF_URL)|
          }" README.md

      - name: Commit changes
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add README.md
          git commit -m "Update trending GIF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
